sudo: required

language: c++

services:
  - docker

before_install:
- docker build -t ff .

script:
  - docker run ff /bin/bash -c "cmake --build . && ./run_tests &&
    lcov --directory . --capture --output-file coverage.info &&
    lcov --remove coverage.info '/usr/*' '*/test/*/*' '*/deps/*' '*/include/*' --output-file coverage.info &&
    lcov --list coverage.info && coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info"
