sudo: required

language: c++

services:
  - docker

before_install:
- docker build -t ff .

script:
  - docker run ff /bin/bash -c "cmake --build . && kcov --exclude-pattern=/usr/include,test,include --coveralls-id=$TRAVIS_JOB_ID coverage ./run_tests"
